services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_service
    depends_on:
      - mongodb
    ports:
      - "8060:8060"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - MONGO_DATABASE=athle_database
      - MONGO_COLLECTION=results
    command: >
      bash -c "
      python check_data.py && 
      if python -c 'from check_data import check_data_count; print(check_data_count())' | grep -q True; then
        echo 'Données suffisantes, lancement direct du Dashboard...' &&
        python main.py;
      else
        echo 'Pas assez de données, exécution complète...' &&
        cd FFA &&
        scrapy crawl competition_results &&
        python main.py;
      fi
      "

volumes:
  mongo-data:
