version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_service
    depends_on:
      - mongodb
    ports:
      - "8060:8060"
    volumes:
      - shared_data:/shared  # Volume partagé pour les fichiers générés
    command: >
      bash -c "
      cd FFA &&
      echo 'Lancement de Scrapy...' &&
      scrapy crawl competition_results -o Course2.csv &&
      echo 'Scrapy terminé, lancement du Dashboard...' &&
      cd .. &&
      python3 main.py
      "

volumes:
  shared_data:
  mongo-data:
