version: '3.9'

services:
  scrapy-service:
    build:
      context: ./Projet_Scrap
      dockerfile: Dockerfile
    container_name: scrapy_service
    volumes:
      - shared_data:/shared  # Monte le volume dans /shared
    command: >
      sh -c "
      cd FFA && scrapy crawl Extract_Course -o Course.csv &&
      echo 'Fichier Course.csv créé :' && ls -la &&
      cp Course.csv /shared/Docker_results_laver.csv &&
      echo 'Fichier déplacé vers volume partagé : /shared' && ls -la /shared
      "

  dashboard-service:
    build:
      context: ./DashBoard_Scrapy
      dockerfile: Dockerfile
    container_name: dashboard_service
    depends_on:
      - scrapy-service
    ports:
      - "8060:8060"
    volumes:
      - shared_data:/shared  # Monte le volume dans /shared
    command: ["python", "main.py"]

volumes:
  shared_data:  # Déclaration du volume partagé
