services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  scrapy-service:
    build:
      context: ./Projet_Scrap
      dockerfile: Dockerfile
    container_name: scrapy_service
    volumes:
      - shared_data:/shared  # Monte le volume dans /shared
    command: >
      sh -c "
      cd FFA &&
      rm -f Course_Docker.csv && scrapy crawl Extract_Course -o Course_Docker.csv &&
      echo 'Fichier Course_Docker.csv créé :' && ls -la &&
      cp Course_Docker.csv /shared/Course_Docker.csv &&
      cd .. &&
      python Extract_Coureur_Mongo.py &&
      python Lavage_Mongo.py &&
      python ExportCSV.py --output /shared/Docker_results_laver.csv &&
      echo 'Fichier déplacé vers volume partagé : /shared' && ls -la /shared
      "

  dashboard-service:
    build:
      context: ./DashBoard_Scrapy
      dockerfile: Dockerfile
    container_name: dashboard_service
    depends_on:
      - scrapy-service
    ports:
      - "8060:8060"
    volumes:
      - shared_data:/shared  # Monte le volume dans /shared
    command: >
      /bin/sh -c "sh /app/wait_for_file.sh && python3 /app/main.py"

volumes:
  shared_data: # Déclaration du volume partagé
  mongo-data:

