apiVersion: apps/v1
kind: Deployment
metadata:
  name: dash-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dash
  template:
    metadata:
      labels:
        app: dash
    spec:
      containers:
      - name: dash
        image: locquetr123/dash-app:latest  # ✅ Ton image DockerHub
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb-service:27017/"
        - name: ELASTICSEARCH_URL
          value: "http://elasticsearch-service:9200"
        ports:
        - containerPort: 8060
---
apiVersion: v1
kind: Service
metadata:
  name: dash-service
spec:
  selector:
    app: dash
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8060
  type: LoadBalancer
